### ISSUE TITLE
Allow for detekt config

### ISSUE THREAD

**Issue by L-Andrade** [natiginfo/action-detekt-all#1]
Hey!

I was trying out your action, but I'd like to run it with a config. Is it possible to add this feature? I gave it a few tries myself but I don't understand much about Actions yet.

Thanks in advance.

**Comment by natiginfo** [comment]
Hi!

With current version of this action, you cannot set configuration. However, it's in enhancements list now. I'll start working on it and update this issue whenever the new version is ready.

Thank you for creating the issue!

**Comment by natiginfo** [comment]
Hi!

I added "Usage with CLI parameters" section to README which can be helpful: https://github.com/natiginfo/action-detekt-all#usage-with-cli-parameters.

Moreover, if you would like to see example workflow, you can check [this](https://github.com/natiginfo/Checkpoint/compare/chore/detekt-arguments) out.

Thank you for bringing up the issue!
