### ISSUE TITLE
Using the detekt/sarif4j  plugin

### ISSUE THREAD

**Issue by swinton** [natiginfo/action-detekt-all#14]
detekt `1.15.0-RC1` [introduces support for SARIF](https://github.com/detekt/detekt/issues/3045#issuecomment-742336959) via [the `sarif4j` plugin](https://github.com/detekt/sarif4j).

It would be great to add this plugin to this `action-detekt-all`, which would allow the detekt analysis to be submitted to GitHub's code scanning feature, which [requires a SARIF report](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github#about-sarif-file-uploads-for-code-scanning).

My initial thoughts are to simply enhance the Dockerfile to download the latest `detekt-report-sarif.jar` plugin release and include it in the container image.

Happy to submit a PR for this, but wanted to check first, to see if you had any concerns / thoughts on this.

**Comment by natiginfo** [comment]
Hi Steve,

First of all, thanks for creating issue about `SARIF` support!

I haven't had time to try [that](https://github.com/detekt/sarif4j) out yet. However, I don't see any issues on downloading latest `detekt-report-sarif.jar` plugin release and including it in the container image.

If you want, you can submit PR. I'm happy to review it.

**Comment by arturbosch** [comment]
Hi @swinton and @natiginfo ,
`detekt-core` bundles the sarif plugin now with 1.15.0-RC2+.
So no update is needed here anymore :)

**Comment by swinton** [comment]
> `detekt-core` bundles the sarif plugin now with 1.15.0-RC2+.

Great to know!

> So no update is needed here anymore :)

Do we still need to bundle [the `detekt-core` JAR](https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-core/1.15.0-RC2) file into the container image?

**Comment by swinton** [comment]
> Do we still need to bundle [the `detekt-core` JAR](https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-core/1.15.0-RC2) file into the container image?

Nope, we don't! https://github.com/natiginfo/action-detekt-all/pull/16#issuecomment-747515810
