### ISSUE TITLE
Support for detekt 1.16.0 not present

### ISSUE THREAD

**Issue by sasa-fajkovic** [natiginfo/action-detekt-all#19]
Please add the support for 1.16.0 which is the latest stable version now.

**Comment by pfaefflin-mms** [comment]
Please create 1.16.0 release for this action, as dependabot already suggests an update.

**Comment by natiginfo** [comment]
Hi @sasa-fajkovic, @pfaefflin-mms!

There is a problem with release automation, and I just manually added missing releases.

Thanks for your patience.
